#!/usr/bin/env bash
# craft-progress.sh — Sync craft pipeline progress to docs/PROGRESS.md
# Triggered on PostToolUse (Write/Edit) when workspace files change.
# Reads .state.yaml files and updates progress tracking.

set -euo pipefail

TOOL_NAME="${1:-}"
PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
PROGRESS_FILE="$PROJECT_ROOT/docs/PROGRESS.md"
WORKSPACE_DIR="$PROJECT_ROOT/workspace"

# Only process Write/Edit
[[ "$TOOL_NAME" != "Write" && "$TOOL_NAME" != "Edit" ]] && exit 0

# Check if a workspace file was modified
INPUT=$(cat /dev/stdin 2>/dev/null || echo "")
if ! echo "$INPUT" | grep -q 'workspace/'; then
  exit 0
fi

# Only update if workspace directory exists and has projects
[[ ! -d "$WORKSPACE_DIR" ]] && exit 0

# Find all project state files
STATE_FILES=$(find "$WORKSPACE_DIR" -name ".state.yaml" -maxdepth 2 2>/dev/null || true)
[[ -z "$STATE_FILES" ]] && exit 0

# Ensure docs directory exists
mkdir -p "$(dirname "$PROGRESS_FILE")"

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Generate progress report
{
  echo "# Craft Pipeline Progress"
  echo ""
  echo "> Auto-generated by craft-progress.sh at $TIMESTAMP"
  echo ""

  while IFS= read -r state_file; do
    PROJECT=$(basename "$(dirname "$state_file")")
    CURRENT_STATE=$(grep -oP 'current_state:\s*\K\S+' "$state_file" 2>/dev/null || echo "unknown")
    PHASE=$(grep -oP 'phase:\s*\K\S+' "$state_file" 2>/dev/null || echo "-")

    # Map state to progress percentage
    case "$CURRENT_STATE" in
      init)           PCT=0;  STATUS="Not started" ;;
      analyzing)      PCT=10; STATUS="Phase 1: Analyzing..." ;;
      analyzed)       PCT=25; STATUS="Phase 1: Complete" ;;
      designing)      PCT=35; STATUS="Phase 2: Designing..." ;;
      design_review)  PCT=45; STATUS="Phase 2: Awaiting review" ;;
      building)       PCT=55; STATUS="Phase 3: Building..." ;;
      validating)     PCT=70; STATUS="Phase 3.5: Validating..." ;;
      build_review)   PCT=80; STATUS="Phase 3.5: Awaiting review" ;;
      deploying)      PCT=90; STATUS="Phase 4: Deploying..." ;;
      done)           PCT=100; STATUS="Complete" ;;
      paused)         PCT=-1; STATUS="Paused" ;;
      failed)         PCT=-1; STATUS="Failed" ;;
      cancelled)      PCT=-1; STATUS="Cancelled" ;;
      *)              PCT=0;  STATUS="Unknown ($CURRENT_STATE)" ;;
    esac

    echo "## $PROJECT"
    echo ""
    if [[ $PCT -ge 0 ]]; then
      # Generate progress bar
      FILLED=$((PCT / 5))
      EMPTY=$((20 - FILLED))
      BAR=$(printf '█%.0s' $(seq 1 $FILLED 2>/dev/null) || true)
      SPACE=$(printf '░%.0s' $(seq 1 $EMPTY 2>/dev/null) || true)
      echo "- **State**: \`$CURRENT_STATE\` | **Phase**: $PHASE"
      echo "- **Progress**: [$BAR$SPACE] $PCT%"
      echo "- **Status**: $STATUS"
    else
      echo "- **State**: \`$CURRENT_STATE\`"
      echo "- **Status**: $STATUS"
    fi
    echo ""

  done <<< "$STATE_FILES"

} > "$PROGRESS_FILE"

exit 0
